# Generated by Django 2.0.7 on 2018-07-27 17:08

import camp_registration.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('camps', '0002_auto_20180718_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('rules_accepted', models.BooleanField(default=False, validators=[camp_registration.models.validate_true])),
                ('present_participants', models.PositiveIntegerField(null=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camps.Camp')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Clan')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField()),
                ('printed', models.BooleanField(default=False)),
                ('registrated', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camps.Fee')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camp_registration.Registration')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camp_registration.TicketInfo'),
        ),
    ]
