# Generated by Django 2.1.5 on 2019-03-23 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'default_permissions': 'view',
            },
        ),
        migrations.CreateModel(
            name='Diocese',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'default_permissions': 'view',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('diocese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Diocese')),
            ],
            options={
                'default_permissions': 'view',
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=4, max_digits=4)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Camp')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('comment', models.TextField(blank=True, max_length=1000, null=True)),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('present_participants', models.PositiveIntegerField(null=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Camp')),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Clan')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered', models.DateTimeField(null=True)),
                ('issued', models.BooleanField()),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TicketInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Fee')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Registration')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.TicketInfo'),
        ),
        migrations.AddField(
            model_name='clan',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.District'),
        ),
    ]
