# Generated by Django 2.1.5 on 2020-03-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_camp_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='fee',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
