# Generated by Django 3.2 on 2022-08-10 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200322_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('printed', models.BooleanField()),
                ('annotated_id', models.PositiveIntegerField(null=True)),
                ('status', models.CharField(choices=[('OK', 'Workshop OK'), ('FE', 'Workshop fehlt'), ('NO', 'Workshop nicht OK'), ('UN', 'Workshop unklar')], default='FE', max_length=2)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.registration')),
            ],
        ),
    ]
