# Generated by Django 3.2 on 2022-08-11 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220810_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopPrintBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.camp')),
            ],
        ),
        migrations.AlterField(
            model_name='workshop',
            name='printed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.workshopprintbatch'),
        ),
    ]
