# Generated by Django 3.2 on 2022-08-12 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20220811_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registered_participants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registration',
            name='clan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.clan'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='present_participants',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
