# Generated by Django 2.0.7 on 2018-07-21 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('camps', '0002_auto_20180718_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('clan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Clan')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField()),
                ('printed', models.BooleanField()),
                ('registrated', models.DateTimeField(null=True)),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camps.Fee')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.Registration')),
            ],
        ),
        migrations.CreateModel(
            name='TicketInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camps.Fee')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registration.Registration')),
            ],
        ),
    ]
