# Generated by Django 2.0.7 on 2018-07-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20180723_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='rules_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticketinfo',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
