# Generated by Django 2.0.7 on 2018-07-24 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20180724_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='registration',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_info',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='registration.TicketInfo'),
            preserve_default=False,
        ),
    ]
