# Generated by Django 2.0.7 on 2018-07-27 09:26

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20180724_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='present_participants',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='comment',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registration',
            name='rules_accepted',
            field=models.BooleanField(default=False, validators=[registration.models.validate_true]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='printed',
            field=models.BooleanField(default=False),
        ),
    ]
