# Generated by Django 2.0.7 on 2018-07-18 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camp',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
